# Generated by Django 5.1.4 on 2025-01-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayTao', models.DateField()),
                ('maKH', models.IntegerField()),
                ('maNV', models.IntegerField()),
                ('tongTien', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNV', models.IntegerField()),
                ('hoTen', models.CharField(max_length=100)),
            ],
        ),
    ]
