# Generated by Django 4.2.19 on 2025-02-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JS_Manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bangGiaVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayCapNhat', models.DateTimeField(auto_now=True)),
                ('loaiVang', models.CharField(default='Vàng 9999', max_length=100)),
                ('giaMua', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('giaBan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('donVi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='baoHanh',
            fields=[
                ('maBH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('donHangLienKet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chuongTrinhKhuyenMai',
            fields=[
                ('maKM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('moTa', models.TextField()),
                ('ngayBatDau', models.DateField()),
                ('ngayKetThuc', models.DateField()),
                ('tyLeChietKhau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='heThong',
            fields=[
                ('maAD', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='khachHang',
            fields=[
                ('maKH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('soDT', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('diemTichLuy', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='loaiSP',
            fields=[
                ('maLoaiSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenLoaiSP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nhanVien',
            fields=[
                ('maNV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('quayHangPhuTrach', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='quanLy',
            fields=[
                ('maQL', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('quayHangPhuTrach', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='thongKeDoanhThu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ngayCapNhat', models.DateTimeField(auto_now=True)),
                ('ngay', models.DateField()),
                ('tongDoanhThu', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tongLoiNhuan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('soDonHang', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thongKeHieuSuatBanHang',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ngayCapNhat', models.DateTimeField(auto_now=True)),
                ('maNV', models.CharField(max_length=50)),
                ('soDonHang', models.IntegerField()),
                ('tongDoanhThu', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tongSoLuong', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thongKeKhachHang',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ngayCapNhat', models.DateTimeField(auto_now=True)),
                ('maKH', models.CharField(max_length=50)),
                ('tongSoDon', models.IntegerField()),
                ('tongGiaTri', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ngayMuaGanNhat', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thongKeKhuyenMai',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ngayCapNhat', models.DateTimeField(auto_now=True)),
                ('maKM', models.CharField(max_length=50)),
                ('soLuotSuDung', models.IntegerField()),
                ('tongGiaTriGiam', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ngayBatDau', models.DateField()),
                ('ngayKetThuc', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thongKeMuaLaiHang',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ngayCapNhat', models.DateTimeField(auto_now=True)),
                ('maSP', models.CharField(max_length=50)),
                ('soLanMua', models.IntegerField()),
                ('tongSoLuong', models.IntegerField()),
                ('tongGiaTri', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sanPham',
            fields=[
                ('maSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenSP', models.CharField(max_length=1000)),
                ('trongLuong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tienCong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tienDa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barcodeSP', models.CharField(max_length=10)),
                ('maLoaiSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.loaisp')),
            ],
        ),
        migrations.CreateModel(
            name='quayHang',
            fields=[
                ('maQH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('viTriQH', models.CharField(max_length=1000)),
                ('danhSachNV', models.JSONField(default=dict)),
                ('danhSachSP', models.JSONField(default=dict)),
                ('maQL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.quanly')),
            ],
        ),
        migrations.CreateModel(
            name='hoaDonMuaLai',
            fields=[
                ('maHD', models.CharField(default='DEFAULT_VALUE', max_length=10, primary_key=True, serialize=False)),
                ('ngayTao', models.DateField()),
                ('tongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.khachhang')),
                ('maNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='hoaDon',
            fields=[
                ('maHD', models.CharField(default='DEFAULT_VALUE', max_length=10, primary_key=True, serialize=False)),
                ('ngayTao', models.DateField()),
                ('tongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.khachhang')),
                ('maNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='donHang',
            fields=[
                ('maDH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngayTao', models.DateField()),
                ('danhSachSPTrongDH', models.JSONField()),
                ('chietKhauKM', models.FloatField()),
                ('chietKhauDB', models.FloatField()),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.khachhang')),
                ('maNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='chiTietHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenSP', models.CharField(max_length=1000)),
                ('soLuong', models.IntegerField()),
                ('giaCa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.hoadon')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='chiTietDH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenSP', models.CharField(max_length=1000)),
                ('soLuong', models.IntegerField()),
                ('maDH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.donhang')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='chiTietBH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayTao', models.DateField()),
                ('ngayKetThuc', models.DateField()),
                ('danhSachLienKet', models.JSONField(default=dict)),
                ('trangThai', models.BooleanField()),
                ('maBH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.baohanh')),
            ],
        ),
    ]
