# Generated by Django 5.1.4 on 2025-01-15 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JS_Manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bangGiaVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayCapNhat', models.DateTimeField()),
                ('giaVang', models.JSONField()),
                ('donVi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bangThongKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doanhThuNV', models.JSONField(default=dict)),
                ('doanhThuQL', models.JSONField(default=dict)),
                ('doanhThuQH', models.JSONField(default=dict)),
                ('tongDoanhThu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='baoHanh',
            fields=[
                ('maBH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('donHangLienKet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chiTietBH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayTao', models.DateField()),
                ('ngayKetThuc', models.DateField()),
                ('danhSachLienKet', models.JSONField(default=dict)),
                ('trangThai', models.BooleanField()),
                ('maBH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.baohanh')),
            ],
        ),
        migrations.CreateModel(
            name='chiTietDH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenSP', models.CharField(max_length=1000)),
                ('soLuong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chiTietHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenSP', models.CharField(max_length=1000)),
                ('soLuong', models.IntegerField()),
                ('giaCa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='chuongTrinhKhuyenMai',
            fields=[
                ('maKM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('moTa', models.TextField()),
                ('ngayBatDau', models.DateField()),
                ('ngayKetThuc', models.DateField()),
                ('tyLeChietKhau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='donHang',
            fields=[
                ('maDH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngayTao', models.DateField()),
                ('danhSachSPTrongDH', models.JSONField()),
                ('chietKhauKM', models.FloatField()),
                ('chietKhauDB', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='heThong',
            fields=[
                ('maAD', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='hoaDon',
            fields=[
                ('maHD', models.CharField(default='DEFAULT_VALUE', max_length=10, primary_key=True, serialize=False)),
                ('ngayTao', models.DateField()),
                ('tongTien', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='khachHang',
            fields=[
                ('maKH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('soDT', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('diemTichLuy', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='loaiSP',
            fields=[
                ('maLoaiSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenLoaiSP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nhanVien',
            fields=[
                ('maNV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('quayHangPhuTrach', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='quanLy',
            fields=[
                ('maQL', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('quayHangPhuTrach', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='quayHang',
            fields=[
                ('maQH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('viTriQH', models.CharField(max_length=1000)),
                ('danhSachNV', models.JSONField(default=dict)),
                ('danhSachSP', models.JSONField(default=dict)),
                ('maQL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.quanly')),
            ],
        ),
        migrations.CreateModel(
            name='sanPham',
            fields=[
                ('maSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenSP', models.CharField(max_length=1000)),
                ('trongLuong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tienCong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tienDa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barcodeSP', models.CharField(max_length=10)),
                ('maLoaiSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.loaisp')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Bill_Detail',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='chitietdh',
            name='maDH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.donhang'),
        ),
        migrations.AddField(
            model_name='chitiethd',
            name='maHD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.hoadon'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='maKH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.khachhang'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='maKH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.khachhang'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='maNV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.nhanvien'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='maNV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.nhanvien'),
        ),
        migrations.AddField(
            model_name='chitiethd',
            name='maSP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.sanpham'),
        ),
        migrations.AddField(
            model_name='chitietdh',
            name='maSP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.sanpham'),
        ),
    ]
