# Generated by Django 5.1.4 on 2025-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "JS_Manage",
            "0002_banggiavang_bangthongke_baohanh_chitietbh_chitietdh_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banggiavang",
            name="giaVang",
        ),
        migrations.AddField(
            model_name="banggiavang",
            name="giaBan",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="banggiavang",
            name="giaMua",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="banggiavang",
            name="loaiVang",
            field=models.CharField(default="Vàng 9999", max_length=100),
        ),
    ]
