# Generated by Django 4.2.19 on 2025-02-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JS_Manage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuongtrinhkhuyenmai',
            name='maKM',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thongkehieusuatbanhang',
            name='maNV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.nhanvien'),
        ),
        migrations.AlterField(
            model_name='thongkekhachhang',
            name='maKH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.khachhang'),
        ),
        migrations.AlterField(
            model_name='thongkekhuyenmai',
            name='maKM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.chuongtrinhkhuyenmai'),
        ),
        migrations.AlterField(
            model_name='thongkemualaihang',
            name='maSP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JS_Manage.sanpham'),
        ),
    ]
